### PR TITLE
Support grouping dot and blank imports at the end

### LINKED ISSUE #65: Group dot imports
AFAICT gci is not able to group dot imports together. It would be nice to be able to configure this.

### PR DESCRIPTION
**Pull request by mnencia**
Closes #65

### CODE REVIEW

**Comment by daixiang0** [comment]
@mnencia thanks for your contribution! 

Codes looks good overall, could you help update README(sections, help command and so on)?

**Comment by mnencia** [comment]
@daixiang0, thanks for the review. I've added the documentation.

**Comment by daixiang0** [comment]
@mnencia LGTM, thanks for your contribution!

**Comment by chialiyun** [comment]
hi @mnencia / @daixiang0 , I am getting this error 

>  * can't run linter goanalysis_metalinter: gci: failed to parse section "Blank": section alias "Blank" not registered with parser


may I ask what am I missing?

I have the following config:
```
linters-settings:
  gci:
    sections:
      - Blank
    custom-order: true
```

**Comment by daixiang0** [comment]
@chialiyun which version of golangci-lint do you use?

**Comment by chialiyun** [comment]
@daixiang0 i am using the latest: `golangci-lint has version v1.44.2 built from (unknown, mod sum: "h1:MzvkDt1j1OHkv42/feNJVNNXRFACPp7aAWBWDo5aYQw=") on (unknown)`

i installed using brew

**Comment by daixiang0** [comment]
@chialiyun 1.44.2 does not include this feature :( You can download binary directly to try the latest version which includes this feature.

**Pull request merged**
