### PR TITLE
fix: bump version for v0.9.2 to align '--version' with the tagged installation

### LINKED ISSUE #143: v0.9.1 indicates version is v0.9.0 with `--version` flag
### What version of GCI are you using?

<pre>
go install github.com/daixiang0/gci@v0.9.1
gci --version
> gci version 0.9.0
</pre>

### Reproduce Steps

<pre>
go install github.com/daixiang0/gci@v0.9.1
gci --version
> gci version 0.9.0
</pre>

### What did you expect to see?

<pre>
go install github.com/daixiang0/gci@v0.9.1
gci --version
> gci version 0.9.1
</pre>

### What did you see instead?

<pre>
go install github.com/daixiang0/gci@v0.9.1
gci --version
> gci version 0.9.0
</pre>

### PR DESCRIPTION
**Pull request by jufemaiz**
Resolves #143

### CODE REVIEW

**Comment by daixiang0** [comment]
@jufemaiz please fix DCO then we can make it land.

**Comment by jufemaiz** [comment]
@daixiang0 have done. Please advise.

**Comment by daixiang0** [comment]
@jufemaiz thanks for your contribution!

**Comment by jufemaiz** [comment]
Thanks for a great package!

**Pull request merged**
