### PR TITLE
optimize detect import blocks

### PR DESCRIPTION
**Pull request by daixiang0**
- optimize import blocks detection logic
- introduce breaking change: remove isolated comments

Signed-off-by: Loong <loong.dai@intel.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
Fix #119

**Comment by daixiang0** [comment]
@avorima which version do you  use?

**Comment by avorima** [comment]
I tested with version 0.8.3, but it looks like the latest version 0.9.0 no longer has any issues with the example

**Comment by daixiang0** [comment]
Thanks, let's use the latest version.

**Pull request merged**
