### PR TITLE
replace log with zap

### PR DESCRIPTION
**Pull request by glightfoot**
In #52, it was suggested to try Zap instead of logrus. While the performance difference is inconsequential, I threw this together to show what it would look like. The structured logging in Zap isn't really useful since this is just a command line tool, and zap seems to always format fields as JSON. 

Like with logrus, all logs are sent to stderr.

Here's some sample output:
```
$ dist/gci print pkg/gci/format.go --debug >/dev/null 
2022-03-10T14:20:04.266-0800    DEBUG   gci/gci.go:112  Loaded File: pkg/gci/format.go
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:48        Parsed imports in file: ["bytes" "fmt" "strings" "github.com/daixiang0/gci/pkg/constants" "github.com/daixiang0/gci/pkg/gci/imports" "github.com/daixiang0/gci/pkg/gci/sections" "github.com/daixiang0/gci/pkg/gci/specificity" "go.uber.org/zap"]
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:72        Matched import "bytes" to section Standard
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:72        Matched import "fmt" to section Standard
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:72        Matched import "strings" to section Standard
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:72        Matched import "github.com/daixiang0/gci/pkg/constants" to section Default
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:72        Matched import "github.com/daixiang0/gci/pkg/gci/imports" to section Default
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:72        Matched import "github.com/daixiang0/gci/pkg/gci/sections" to section Default
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:72        Matched import "github.com/daixiang0/gci/pkg/gci/specificity" to section Default
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:72        Matched import "go.uber.org/zap" to section Default
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:82        Formatting section Standard with imports: ["bytes" "fmt" "strings"]
2022-03-10T14:20:04.266-0800    DEBUG   gci/format.go:82        Formatting section Default with imports: ["github.com/daixiang0/gci/pkg/constants" "github.com/daixiang0/gci/pkg/gci/imports" "github.com/daixiang0/gci/pkg/gci/sections" "github.com/daixiang0/gci/pkg/gci/specificity" "go.uber.org/zap"]
```

### CODE REVIEW

**Comment by daixiang0** [comment]
Please sign commits, sorry for this switch.

**Comment by glightfoot** [comment]
I added a log package so the zap logger doesn't replace any globals in case someone is using gci as a package

**Comment by daixiang0** [comment]
@ldez is `zap` good for you?

**Comment by daixiang0** [comment]
ping @ldez

**Pull request merged**
